### DISCUSSION TITLE
Trailing commas

### DISCUSSION THREAD

**Discussion by jk-inazczech** [sibiraj-s/vscode-scss-formatter#2] [Feature request] [answered]
Hi,
I found a kind of configuration bug in this extension. The use of Prettier should be with `trailingComma` set to `none`, because when `map-get()` contains comma after the last parameter, then it's not compilable in Visual Studio by Web Compiler.

I filed an issue about it (https://github.com/prettier/prettier/issues/10096). It's an option of Prettier, not their bug.

Thank you for feedback

**Comment by sibiraj-s** [comment]
AFIK, SASS supports trailing commas, so it shouldn't be a problem. Which SASS compiler are you using?

**Comment by sibiraj-s** [comment]
I tried your input here https://www.sassmeister.com/ which uses dart-sass

```scss
$ts-font-size: (
  "large": 16px,
  "normal": 14px,
);

$local-name-max-height: calc(
  5 * #{map-get(
      $map: $ts-font-size,
      $key: "large",
    )}
);

.item {
    height: $local-name-max-height;
}
```

output is as expected

```css
.item {
  height: calc( 5 * 16px );
}
```
