### DISCUSSION TITLE
block-closing-brace-newline-after

### DISCUSSION THREAD

**Discussion by kevinblackdesk** [sibiraj-s/vscode-scss-formatter#4] [Q&A]
Saw no issues on this repository so I'm posting this here.

VSCode: 1.52.1
SCSS Formatter: v2.1.0

```scss
@each $breakpoint, $container-max-width in $container-max-widths {
    @include media-breakpoint-up($breakpoint, $grid-breakpoints) {
      @if $breakpoint==lg {
        &__inner {
          max-width: $container-max-width / 2;
        }
      }
      @else if $breakpoint==xl {
        &__inner {
          max-width: $container-max-width / 2;
        }
      }
      @else if $breakpoint==xxl {
        &__inner {
          max-width: $container-max-width / 2;
        }
      }
    }
  }
 ```
  
  gets formatted to
  
  ```scss
  @each $breakpoint, $container-max-width in $container-max-widths {
    @include media-breakpoint-up($breakpoint, $grid-breakpoints) {
      @if $breakpoint==lg {
        &__inner {
          max-width: $container-max-width / 2;
        }
      } @else if $breakpoint==xl {
        &__inner {
          max-width: $container-max-width / 2;
        }
      } @else if $breakpoint==xxl {
        &__inner {
          max-width: $container-max-width / 2;
        }
      }
    }
  }
  ```
  
 However.. when I run `stylelint "resources/assets/**/*.scss"` I get the following error's:
 
 ```
 38:8  ✖  Expected newline after "}"   block-closing-brace-newline-after
 42:8  ✖  Expected newline after "}"   block-closing-brace-newline-after
 ```
 
 
Howcome?
