### ISSUE TITLE
error by format

### ISSUE THREAD

**Issue by qq326943819** [sibiraj-s/vscode-scss-formatter#10]
![image](https://user-images.githubusercontent.com/32457006/145230671-a0498c7d-5b34-4f99-85e1-97bae11577ad.png)

```css
@forward "~element-plus/theme-chalk/src/common/var.scss" with (
  $colors: (
    'primary': (
      'base': $color-primary,
    ),
    'info': (
      'base':$color-info,
    ),
    'success':(
      'base':$color-success,
    )
  )
);

@use "~element-plus/theme-chalk/src/index.scss" as *;

:root {
  --el-border-color-base: #097189;
  --el-text-color-regular: #729ea8;
  --el-border-color-light: #137993;
}

.el-button {
  --el-font-size-base: 26px;
  width: 9.375rem;
  height: 3.75rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;

  &.el-button--small {
    width: 8.125rem;
    padding: initial;
    font-size: var(--el-font-size-base);
  }

  & + & {
    margin-left: 30px;
  }
}
.el-button--text {
  border-color: transparent;
  color: #c3383e !important;
  background: transparent;
  padding-left: 0;
  padding-right: 0;
  font-size: 22px;
}
.el-button--default {
  background-color: #115577;
  color: #c2dbe4;
}

.el-form {
  --el-form-label-font-size: 24px;
  --el-text-color-regular: #eafafd;

  .el-input,
  .el-input__inner {
    width: 18.875rem;
    line-height: 3.75rem;
    height: 3.75rem;
    background: rgba(13, 51, 70, 0.8);
    border: 1px solid #097189;
    border-radius: 6px;
    --el-font-size-base: 24px;
    --el-input-font-color: #729ea8;

    &::placeholder {
      color: inherit;
    }
  }

  .el-range-editor.el-input__inner {
    width: 24.25rem;
    --el-text-color-primary: #729ea8;
    align-items: center;

    .el-range-separator {
      height: initial;
    }

    .el-range-input {
      background-color: transparent;
    }
  }
}

.el-form-item {
  margin-bottom: 0;
}

.el-form--inline .el-form-item {
  align-items: center;
}

.el-pagination {
  align-items: center;
  display: flex;

  --el-pagination-font-size: 18px;
  --el-pagination-hover-color: #fff;
  --el-pagination-font-color: #729ea8;
  --el-pagination-button-color: var(--el-pagination-font-color);
  --el-pagination-button-disabled-color: var(--el-pagination-font-color);
  --el-pagination-background-color: #0d3346;
  --el-pagination-button-disabled-background-color: var(
    --el-pagination-background-color
  );
  --el-pagination-button-height: 3rem;
  --el-pagination-hover-color: #fff;

  .el-pagination__sizes {
    display: inline-flex !important;
    align-items: center;
  }

  .el-select--mini,
  .select-trigger,
  .el-input--mini,
  .el-input__inner {
    height: 100%;
    line-height: var(--el-pagination-button-height);
  }

  button,
  .number {
    width: 6.25rem;
    height: 3rem;
    padding: 0 !important;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    margin: 0 7px !important;
    border-radius: 6px;
    border: 1px solid #097189 !important;
  }

  .number {
    width: 3rem;
    &.active {
      background-color: #23a9c7;
    }
  }
}

.el-input {
  --el-input-background-color: #0d3346;
  --el-border-color-base: #097189;
  --el-border-color-light: var(--el-border-color-base);
}

.el-select {
  --el-select-input-focus-border-color: #097189;
}

.el-select-dropdown__list {
  margin: 0 !important;
}

.el-select-dropdown__item {
  --el-background-color-base: #33a8b4;
  --el-color-primary: #fff;
  --el-text-color-regular: var(--el-color-primary);
}

.el-select__popper.el-popper[role="tooltip"] {
  background-color: #137993;

  .el-popper__arrow {
    display: none;
  }
}
.el-table {
  --el-border-color-light: #33a8b4;
  --el-text-color-regular: #c2f0f8;
  --el-table-border-color: transparent;
  --el-table-border: 1px solid var(--el-table-header-background-color);
  --el-table-font-color: var(--el-text-color-regular);
  --el-table-header-font-color: var(--el-border-color-light);
  --el-table-row-hover-background-color: var(--el-background-color-base);
  --el-table-current-row-background-color: var(--el-color-primary-light-9);
  --el-table-header-background-color: rgba(11, 31, 40, 0.7);
  --el-table-fixed-box-shadow: 0 0 10px rgba(0, 0, 0, 0.12);
  --el-table-background-color: var(--el-table-header-background-color);
  --el-table-tr-background-color: var(--el-table-header-background-color);
  --el-table-expanded-cell-background-color: var(
    --el-table-header-background-color
  );
  --el-table-row-hover-background-color: initial;
  thead {
    font-size: 20px;
    font-weight: 400 !important;
    line-height: 40px;
  }
  .el-table__empty-text {
    line-height: 60px;
    width: 50%;
    color: var(--el-text-color-regular);
  }
  th {
    font-weight: normal;
    border-bottom: 1px solid rgba(28, 86, 106, 0.7) !important;
    padding-bottom: 10px !important;
  }
  tr,
  td {
    font-size: 22px;
  }
  .el-table__cell {
    text-align: center;
  }
}

.el-tabs--border-card {
  --el-tabs-backgroud-color: rgba(11, 31, 40, 0.7);
  background: var(--el-tabs-backgroud-color);
  border: none;
  box-shadow: 0 2px 4px 0 rgb(0 0 0 / 12%), 0 0 6px 0 rgb(0 0 0 / 4%);
  color: #fff;
  .el-tabs__header {
    background-color: rgba(26, 47, 56);
    border-bottom: none;
    margin: 0;
    overflow: hidden;
    .el-tabs__item {
      height: 80px;
      font-size: 20px;
      color: #fff;
      padding-top: 19px;
    }
  }
  .el-tabs__header .el-tabs__item.is-active {
    height: 80px;
    color: #fff;
    border-color: transparent;
    background-color: var(--el-tabs-backgroud-color);
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
  }
  .el-tabs--border-card > .el-tabs__content {
    padding: 10px;
  }
}
// 消息确认框

.el-message-box {
  --el-meaasage-header-color: #fff;
  display: inline-block;
  width: var(--el-messagebox-width);
  padding-bottom: 10px;
  vertical-align: middle;
  background-color: rgba(19, 121, 147, 0.8) !important;
  border-radius: var(--el-messagebox-border-radius);
  border: 1px solid rgba(19, 121, 147);
  font-size: 24px !important;
  box-shadow: var(--el-box-shadow-light);
  text-align: left;
  overflow: hidden;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  color: var(--el-meaasage-header-color);
  width: 640px;
  height: 380px;
  .el-message-box__header {
    position: relative;
    padding: 40px 20px 0 20px;
    .el-message-box__title {
      font-size: 30px;
      line-height: 1;
      color: var(--el-meaasage-header-color);
      line-height: 9px;
    }
    .el-message-box__headerbtn .el-message-box__close {
      color: var(--el-meaasage-header-color);
      font-size: 30px;
    }
  }
  .el-message-box__content {
    // padding: 50px;
    font-size: 24px;
    height: 210px;
    display: flex;
    justify-content: center;
    align-items: center;
    color: #fff;
  }
  .el-message-box__btns {
    padding: 5px 15px 0;
    text-align: center;
    button {
      margin-left: 20px;
    }
  }
}

.el-drawer {
  --el-drawer-background-color: #1c566a;
  position: absolute;
  box-sizing: border-box;
  background-color: var(--el-drawer-background-color);
  display: flex;
  flex-direction: column;
  box-shadow: 0 8px 10px -5px rgb(0 0 0 / 20%), 0 16px 24px 2px rgb(0 0 0 / 14%),
    0 6px 30px 5px rgb(0 0 0 / 12%);
  overflow: hidden;
  transition: all var(--el-transition-duration);
  .el-drawer__header {
    color: #fff;
    font-size: 30px;
  }
  .el-drawer__body {
    color: #fff;
    font-size: 1.5rem;
    flex-direction: column;
    display: flex;
  }
}
.el-checkbox-group {
  display: flex;
  flex-direction: column;
  .el-checkbox__label {
    font-size: 24px;
  }
}

.el-checkbox {
  --el-checkbox-font-size: 30px;
  margin-right: 60px !important;
  height: 40px;
  background: transparent;
}
.el-dialog {
  --el-dialog-width: 50%;
  --el-dialog-margin-top: 15vh;
  --el-color-white: #1c566a;
  --el-dialog-background-color: var(--el-color-white);
  --el-dialog-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
  --el-dialog-title-font-size: 30px;
  --el-dialog-content-font-size: 14px;
  --el-dialog-font-line-height: var(--el-font-line-height-primary);
  --el-dialog-padding-primary: 20px;
  position: relative;
  margin: var(--el-dialog-margin-top, 15vh) auto 50px;
  background: var(--el-dialog-background-color);
  border-radius: var(--el-border-radius-small);
  box-shadow: var(--el-dialog-box-shadow);
  box-sizing: border-box;
  width: var(--el-dialog-width, 50%);
  .el-dialog__title {
    line-height: var(--el-dialog-font-line-height);
    font-size: var(--el-dialog-title-font-size);
    color: #fff;
  }
}
.el-loading-mask {
  background-color: rgba(0, 0, 0, 0.3);
}
```
